(function () {
  "use strict";
  const UW=typeof unsafeWindow!=="undefined"?unsafeWindow:window;
  const FEATURE_ID="script-compat-diagnostic-provider",PROVIDER_ID="script-compat",PROVIDER_SCHEMA_VERSION=1,VERSION="0.1.0",BUILD="0.1.0-kitbash-extra-slots",MAX_REGISTER_TRIES=120,SCRIPT_SCAN_LIMIT=500;
  if(UW.KWScriptCompatDiagnosticProvider&&UW.KWScriptCompatDiagnosticProvider.build===BUILD)return;
  let registered=false,registerTries=0,timer=null;
  function core(){return UW.KWWitchDockDiagnostics||null;}
  function hashText(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,"0");}
  function fnFingerprint(owner,key){
    let fn=null,d=null;try{fn=owner&&owner[key];d=owner?Object.getOwnPropertyDescriptor(owner,key):null;}catch(_){}
    if(typeof fn!=="function")return{present:false};
    let source="";try{source=Function.prototype.toString.call(fn);}catch(_){}
    const compact=source.replace(/\s+/g," ").trim();
    return{present:true,name:fn.name||null,arity:Number(fn.length)||0,sourceLength:source.length,sourceHash:hashText(source),writable:d?d.writable!==false:null,configurable:d?d.configurable!==false:null,noOpShape:/\{\s*\}$/.test(compact)};
  }
  function figureData(){const d=UW.CK&&UW.CK.character&&UW.CK.character.data,out=[];if(d)out.push({key:"primary",data:d});const c=d&&d.children;if(c&&typeof c==="object")for(const[k,v]of Object.entries(c).slice(0,24))if(v&&typeof v==="object"&&v!==d)out.push({key:"child:"+k,data:v});return out;}
  function kitSummary(){
    const rows=[];let total=0,highest=-1,holes=0;
    for(const f of figureData()){const kit=f.data&&f.data.kit,keys=kit&&typeof kit==="object"?Object.keys(kit):[],nums=keys.map(k=>{const m=/^k_(\d+)$/.exec(k);return m?Number(m[1]):null;}).filter(Number.isFinite).sort((a,b)=>a-b);const set=new Set(nums);let local=0;if(nums.length){for(let i=nums[0];i<=nums[nums.length-1];i++)if(!set.has(i))local++;highest=Math.max(highest,nums[nums.length-1]);}total+=nums.length;holes+=local;rows.push({figureKey:f.key,kitRecordCount:nums.length,totalOwnKitKeys:keys.length,highestNumericIndex:nums.length?nums[nums.length-1]:null,holeCount:local});}
    return{figureCount:rows.length,totalKitRecords:total,highestNumericIndex:highest>=0?highest:null,holeCount:holes,figures:rows};
  }
  function extrasSignature(){const scripts=Array.from(document.scripts||[]);let scanned=0,candidates=0,expanded=false;for(const script of scripts.slice(0,SCRIPT_SCAN_LIMIT)){scanned++;if(script.src)continue;const t=String(script.textContent||"");if(!t||!/CK\.KitData/.test(t))continue;candidates++;if(/(?:i|[a-zA-Z_$][\w$]*)\s*<\s*5000/.test(t))expanded=true;}return{scriptsScanned:scanned,inlineCandidates:candidates,expandedLoopSignature:expanded,capBypassSignature:"unverified",scanTruncated:scripts.length>SCRIPT_SCAN_LIMIT};}
  function slotSummary(){const slots=UW.CK&&UW.CK.Options&&UW.CK.Options.slots,rows=slots&&typeof slots==="object"?Object.values(slots):[],hist={};let applicable=0,v3=0,minCount=0;for(const row of rows){if(!row||typeof row!=="object")continue;if(row.allowMonsters){applicable++;const k=String(row.allowMonsters);hist[k]=(hist[k]||0)+1;if(Number(row.allowMonsters)===3)v3++;}if(row.allowMonstersMin!=null)minCount++;}return{slotCount:rows.length,applicableAllowMonstersCount:applicable,value3Count:v3,histogram:hist,allowMonstersMinCount:minCount};}
  function settings(){const s=UW.CK&&UW.CK.Settings;return{artVersionNumber:s&&s.artVersionNumber||null,kitPartCap:s&&Number.isFinite(Number(s.kitPartCap))?Number(s.kitPartCap):null,kitPartMaxPercent:s&&Number.isFinite(Number(s.kitPartMaxPercent))?Number(s.kitPartMaxPercent):null,kitPartMinPercent:s&&Number.isFinite(Number(s.kitPartMinPercent))?Number(s.kitPartMinPercent):null,kitMinScale:s&&Number.isFinite(Number(s.kitMinScale))?Number(s.kitMinScale):null,kitMaxScale:s&&Number.isFinite(Number(s.kitMaxScale))?Number(s.kitMaxScale):null};}
  function safeHeat(){const k=UW.CK&&UW.CK.KitData;if(!k||typeof k.getKitPartHeat!=="function")return{available:false,reason:"getKitPartHeat-unavailable"};try{return{available:true,value:Number(k.getKitPartHeat())};}catch(e){return{available:false,reason:"getKitPartHeat-threw",message:String(e&&e.message?e.message:e).slice(0,500)};}}
  function classKit(s,cap,sig){const effects=[s.kitPartCap===5000,s.kitMinScale===-100,s.kitMaxScale===100,!!(cap.present&&cap.noOpShape&&cap.writable===false&&cap.configurable===false),sig.expandedLoopSignature===true],yes=effects.filter(Boolean).length;return yes===effects.length?"complete":yes===0?"absent":"partial";}
  function classSlots(fp,slots){const f=!!(fp.present&&fp.writable===false&&fp.configurable===false),s=slots.applicableAllowMonstersCount>0&&slots.value3Count===slots.applicableAllowMonstersCount;return f&&s?"complete":(!f&&slots.value3Count===0?"absent":"partial");}
  function freeze(){const CK=UW.CK,s=settings(),cap=fnFingerprint(CK&&CK.KitData,"capKit"),heatFn=fnFingerprint(CK&&CK.KitData,"getKitPartHeat"),sig=extrasSignature(),kit=kitSummary(),heat=safeHeat(),fit=fnFingerprint(CK&&CK.Options,"doesConfigFit"),slots=slotSummary();return{state:{artVersionNumber:s.artVersionNumber,settingsAvailable:!!(CK&&CK.Settings),kitDataAvailable:!!(CK&&CK.KitData),optionsAvailable:!!(CK&&CK.Options),figureCount:kit.figureCount},kitbash:{settings:s,capKit:cap,getKitPartHeat:heatFn,heat,inventory:kit},"kitbash-patch-signatures":sig,"extra-slots":{doesConfigFit:fit,slots},classifications:{kitbash:classKit(s,cap,sig),extraSlots:classSlots(fit,slots)}};}
  function warning(code,message,phase,expected,actual){return{provider:PROVIDER_ID,code,phase,severity:"warning",message,expected:expected==null?null:expected,actual:actual==null?null:actual};}
  function capture(context,frozenSeed){const seed=frozenSeed||freeze(),warnings=[];if(seed.classifications.kitbash==="partial")warnings.push(warning("SCRIPT_COMPAT_KITBASH_OVERRIDE_PARTIAL","Known high-kitbash runtime effects are only partially present.","kitbash","complete","partial"));else if(seed.classifications.kitbash==="absent")warnings.push(warning("SCRIPT_COMPAT_KITBASH_OVERRIDE_ABSENT","Known high-kitbash runtime effects were not detected.","kitbash","complete","absent"));if(seed["kitbash-patch-signatures"].capBypassSignature==="unverified")warnings.push(warning("SCRIPT_COMPAT_KITBASH_EXTRAS_PATCH_UNVERIFIED","The modified extras.js cap-bypass effect cannot be fingerprinted reliably on this build.","kitbash-patch-signatures","verified","unverified"));if(!seed.kitbash.heat.available)warnings.push(warning("SCRIPT_COMPAT_KITBASH_HEAT_READ_FAILED",seed.kitbash.heat.message||seed.kitbash.heat.reason,"kitbash",true,false));if(seed.classifications.extraSlots==="partial")warnings.push(warning("SCRIPT_COMPAT_EXTRA_SLOTS_OVERRIDE_PARTIAL","Known Extra Slots runtime effects are only partially present.","extra-slots","complete","partial"));else if(seed.classifications.extraSlots==="absent")warnings.push(warning("SCRIPT_COMPAT_EXTRA_SLOTS_OVERRIDE_ABSENT","Known Extra Slots runtime effects were not detected.","extra-slots","complete","absent"));return{summary:{artVersionNumber:seed.state.artVersionNumber,kitRecordCount:seed.kitbash.inventory.totalKitRecords,kitHeat:seed.kitbash.heat.available?seed.kitbash.heat.value:null,kitPartCap:seed.kitbash.settings.kitPartCap,kitMinScale:seed.kitbash.settings.kitMinScale,kitMaxScale:seed.kitbash.settings.kitMaxScale,capKitFingerprintPresent:!!seed.kitbash.capKit.present,expandedExtrasSignature:seed["kitbash-patch-signatures"].expandedLoopSignature?"present":"absent",kitbashOverrideHealth:seed.classifications.kitbash,slotCount:seed["extra-slots"].slots.slotCount,allowMonstersHistogram:seed["extra-slots"].slots.histogram,doesConfigFitFingerprintPresent:!!seed["extra-slots"].doesConfigFit.present,extraSlotsOverrideHealth:seed.classifications.extraSlots,warningCodes:warnings.map(w=>w.code)},sections:{state:seed.state,kitbash:seed.kitbash,"kitbash-patch-signatures":seed["kitbash-patch-signatures"],"extra-slots":seed["extra-slots"]},coverage:[{sectionName:"state",status:"captured",reason:null},{sectionName:"kitbash",status:"captured-bounded",reason:"counts-function-fingerprints-and-safe-heat-only"},{sectionName:"kitbash-patch-signatures",status:"partial",reason:"expanded-loop-boolean-only-cap-bypass-unverified"},{sectionName:"extra-slots",status:"captured-bounded",reason:"slot-aggregates-and-function-fingerprint-only"}],warnings,events:[]};}
  function register(){if(registered)return true;const svc=core();if(!svc||typeof svc.registerProvider!=="function")return false;svc.registerProvider({providerId:PROVIDER_ID,providerSchemaVersion:PROVIDER_SCHEMA_VERSION,version:VERSION,build:BUILD,modes:["snapshot"],capabilities:{snapshot:true,comparison:false,allowlistedExternalEffects:["kitbash","extra-slots"]},freeze,capture});registered=true;if(timer){clearInterval(timer);timer=null;}return true;}
  function dispose(){const svc=core();if(registered&&svc&&typeof svc.unregisterProvider==="function"){try{svc.unregisterProvider(PROVIDER_ID);}catch(_){}}registered=false;if(timer)clearInterval(timer);timer=null;return true;}
  UW.KWScriptCompatDiagnosticProvider=Object.freeze({featureId:FEATURE_ID,providerId:PROVIDER_ID,providerSchemaVersion:PROVIDER_SCHEMA_VERSION,version:VERSION,build:BUILD,getState:()=>({featureId:FEATURE_ID,providerId:PROVIDER_ID,version:VERSION,build:BUILD,registered,registerTries,coreAvailable:!!core()}),dispose});
  if(!register())timer=setInterval(()=>{registerTries+=1;if(register()||registerTries>=MAX_REGISTER_TRIES){if(timer)clearInterval(timer);timer=null;}},100);
})();